# Generated by Django 3.1.5 on 2022-01-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-Created']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='Deleted',
        ),
    ]
